spring.application.name=auth-service

spring.datasource.url=jdbc:postgresql://localhost:5432/chat_app_auth
spring.datasource.username=postgres
spring.datasource.password=Chandra@1977

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.format_sql=true

server.port=8081
